import { Chat, Message, Profile, UserStatus } from '@/types';

export const DEMO_CURRENT_USER: Profile = {
  id: 'usr_current_01',
  username: 'dardcor',
  display_name: 'Dardcor Media',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  about: 'Ada! Menggunakan WhatsApp.',
  phone_number: '+62 812 3456 7890',
  is_online: true,
  last_seen: new Date().toISOString(),
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_CONTACTS: Profile[] = [
  {
    id: 'usr_contact_01',
    username: 'sarah_amalia',
    display_name: 'Sarah Amalia',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    about: 'Menikmati hidup dan secangkir kopi ☕',
    phone_number: '+62 821 1122 3344',
    is_online: true,
    last_seen: new Date().toISOString(),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_contact_02',
    username: 'budi_santoso',
    display_name: 'Budi Santoso',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    about: 'Coding, Coffee, Repeat 💻',
    phone_number: '+62 856 9988 7766',
    is_online: false,
    last_seen: new Date(Date.now() - 15 * 60000).toISOString(),
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_contact_03',
    username: 'andi_wijaya',
    display_name: 'Andi Wijaya',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    about: 'Sedang sibuk, hanya pesan mendesak ⏳',
    phone_number: '+62 878 5544 3322',
    is_online: true,
    last_seen: new Date().toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_contact_04',
    username: 'dinda_putri',
    display_name: 'Dinda Putri',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    about: 'Photography & Traveling 📸✈️',
    phone_number: '+62 813 7788 9900',
    is_online: false,
    last_seen: new Date(Date.now() - 2 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_CHATS: Chat[] = [
  {
    id: 'chat_01',
    is_group: false,
    last_message_at: new Date(Date.now() - 2 * 60000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    unread_count: 2,
    other_participant: DEMO_CONTACTS[0],
    participants: [
      {
        id: 'cp_01',
        chat_id: 'chat_01',
        user_id: DEMO_CURRENT_USER.id,
        role: 'member',
        is_pinned: true,
        is_archived: false,
        is_muted: false,
        last_read_at: new Date(Date.now() - 10 * 60000).toISOString(),
        joined_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        profile: DEMO_CURRENT_USER,
      },
      {
        id: 'cp_02',
        chat_id: 'chat_01',
        user_id: DEMO_CONTACTS[0].id,
        role: 'member',
        is_pinned: false,
        is_archived: false,
        is_muted: false,
        last_read_at: new Date().toISOString(),
        joined_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        profile: DEMO_CONTACTS[0],
      },
    ],
    last_message: {
      id: 'msg_01_03',
      chat_id: 'chat_01',
      sender_id: DEMO_CONTACTS[0].id,
      content: 'Halo! Proyek WhatsApp clone Next.js kita sudah hampir selesai ya? Keren banget hasilnya! 🔥',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 2 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 60000).toISOString(),
    },
  },
  {
    id: 'chat_02',
    is_group: true,
    group_name: 'Komunitas Developer Fullstack 🇮🇩',
    group_description: 'Tempat diskusi seputar Next.js, React, Supabase, Tailwind, dan Tech Stack modern.',
    group_avatar_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    created_by: DEMO_CONTACTS[1].id,
    last_message_at: new Date(Date.now() - 25 * 60000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    unread_count: 0,
    participants: [
      {
        id: 'cp_group_01',
        chat_id: 'chat_02',
        user_id: DEMO_CURRENT_USER.id,
        role: 'member',
        is_pinned: true,
        is_archived: false,
        is_muted: false,
        last_read_at: new Date().toISOString(),
        joined_at: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
      {
        id: 'cp_group_02',
        chat_id: 'chat_02',
        user_id: DEMO_CONTACTS[1].id,
        role: 'admin',
        is_pinned: false,
        is_archived: false,
        is_muted: false,
        last_read_at: new Date().toISOString(),
        joined_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        profile: DEMO_CONTACTS[1],
      },
      {
        id: 'cp_group_03',
        chat_id: 'chat_02',
        user_id: DEMO_CONTACTS[2].id,
        role: 'member',
        is_pinned: false,
        is_archived: false,
        is_muted: false,
        last_read_at: new Date().toISOString(),
        joined_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        profile: DEMO_CONTACTS[2],
      },
    ],
    last_message: {
      id: 'msg_02_02',
      chat_id: 'chat_02',
      sender_id: DEMO_CONTACTS[1].id,
      content: 'Teman-teman jangan lupa review skema database.sql yang baru ya!',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 25 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 25 * 60000).toISOString(),
    },
  },
  {
    id: 'chat_03',
    is_group: false,
    last_message_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    unread_count: 0,
    other_participant: DEMO_CONTACTS[1],
    participants: [],
    last_message: {
      id: 'msg_03_01',
      chat_id: 'chat_03',
      sender_id: DEMO_CURRENT_USER.id,
      content: 'Siap mas Budi, sudah saya push ke repository.',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    },
  },
  {
    id: 'chat_04',
    is_group: false,
    last_message_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    unread_count: 0,
    other_participant: DEMO_CONTACTS[3],
    participants: [],
    last_message: {
      id: 'msg_04_01',
      chat_id: 'chat_04',
      sender_id: DEMO_CONTACTS[3].id,
      content: 'Keren banget fotonya! Nanti kirim lewat WhatsApp dokumen ya biar nggak pecah resolusinya.',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date(Date.now() - 86400000).toISOString(),
    },
  },
];

export const DEMO_MESSAGES: { [chatId: string]: Message[] } = {
  chat_01: [
    {
      id: 'msg_01_01',
      chat_id: 'chat_01',
      sender_id: DEMO_CONTACTS[0].id,
      content: 'Hai! Gimana progress aplikasi WhatsApp Web kita hari ini?',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 60 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 60 * 60000).toISOString(),
      sender: DEMO_CONTACTS[0],
    },
    {
      id: 'msg_01_02',
      chat_id: 'chat_01',
      sender_id: DEMO_CURRENT_USER.id,
      content: 'Luar biasa lancar! Skema database.sql di Supabase sudah siap, halaman Login & Register juga sudah lengkap dengan tema asli WhatsApp.',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 45 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 45 * 60000).toISOString(),
      sender: DEMO_CURRENT_USER,
      statuses: [
        {
          id: 'st_01',
          message_id: 'msg_01_02',
          user_id: DEMO_CONTACTS[0].id,
          status: 'read',
          updated_at: new Date(Date.now() - 40 * 60000).toISOString(),
        },
      ],
      reactions: [
        {
          id: 'rx_01',
          message_id: 'msg_01_02',
          user_id: DEMO_CONTACTS[0].id,
          emoji: '❤️',
          created_at: new Date(Date.now() - 40 * 60000).toISOString(),
        },
      ],
    },
    {
      id: 'msg_01_03',
      chat_id: 'chat_01',
      sender_id: DEMO_CONTACTS[0].id,
      content: 'Halo! Proyek WhatsApp clone Next.js kita sudah hampir selesai ya? Keren banget hasilnya! 🔥',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 2 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 60000).toISOString(),
      sender: DEMO_CONTACTS[0],
      reactions: [
        {
          id: 'rx_02',
          message_id: 'msg_01_03',
          user_id: DEMO_CURRENT_USER.id,
          emoji: '👍',
          created_at: new Date(Date.now() - 1 * 60000).toISOString(),
        },
      ],
    },
  ],
  chat_02: [
    {
      id: 'msg_02_01',
      chat_id: 'chat_02',
      sender_id: DEMO_CONTACTS[2].id,
      content: 'Selamat siang rekan-rekan! Selamat bergabung di grup WhatsApp Clone.',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 3600000).toISOString(),
      sender: DEMO_CONTACTS[2],
    },
    {
      id: 'msg_02_02',
      chat_id: 'chat_02',
      sender_id: DEMO_CONTACTS[1].id,
      content: 'Teman-teman jangan lupa review skema database.sql yang baru ya!',
      message_type: 'text',
      is_deleted_for_all: false,
      created_at: new Date(Date.now() - 25 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 25 * 60000).toISOString(),
      sender: DEMO_CONTACTS[1],
    },
  ],
};

export const DEMO_STATUSES: UserStatus[] = [
  {
    id: 'st_01',
    user_id: DEMO_CONTACTS[0].id,
    media_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    caption: 'Liburan singkat di pantai 🌊☀️',
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    expires_at: new Date(Date.now() + 21 * 3600000).toISOString(),
    profile: DEMO_CONTACTS[0],
  },
  {
    id: 'st_02',
    user_id: DEMO_CONTACTS[1].id,
    caption: 'Next.js 15 + Supabase is pure magic ✨🚀',
    background_color: '#005c4b',
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    expires_at: new Date(Date.now() + 19 * 3600000).toISOString(),
    profile: DEMO_CONTACTS[1],
  },
];
